[INFO   ] Logger: Record log in /storage/emulated/0/fest_app_home/.kivy/logs/kivy_19-03-28_9.txt
[INFO   ] Kivy: v1.10.1.dev0, git-ae3665c, 20180425
[INFO   ] Python: v3.6.2 (default, Apr 25 2018, 09:37:02) 
[GCC 7.2.0]
[INFO   ] Factory: 194 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] KivyMD: KivyMD version: 0.1.2
[INFO   ] Text: Provider: sdl2
[INFO   ] OSC: using <thread> for socket
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL ES 2" graphics system
[INFO   ] GL: Backend used <gl>
[INFO   ] GL: OpenGL version <b'OpenGL ES 3.2 v1.r18p0-00cet0.31096d938f6f64bb2ec1de8405ab6460'>
[INFO   ] GL: OpenGL vendor <b'ARM'>
[INFO   ] GL: OpenGL renderer <b'Mali-T880'>
[INFO   ] GL: OpenGL parsed version: 3, 2
[INFO   ] GL: Texture max size <8192>
[INFO   ] GL: Texture max units <16>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] GL: NPOT texture support is available
[INFO   ] Loader: using a thread pool of 2 workers
[INFO   ] Video: Provider: null(['video_ffmpeg', 'video_ffpyplayer'] ignored)
[WARNING] Base: Unknown <android> provider
[INFO   ] Base: Start application main loop
[WARNING] Base: Failed to import "android" module. Could not remove android presplash.
[WARNING] GL: Unpack subimage support is not available
[INFO   ] Base: Leaving application in progress...
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/storage/emulated/0/fest_app_home/main.py", line 263, in <module>
[WARNING] stderr:     total().run()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/kivy/app.py", line 826, in run
[WARNING] stderr:     runTouchApp()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/kivy/base.py", line 502, in runTouchApp
[WARNING] stderr:     EventLoop.window.mainloop()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 723, in mainloop
[WARNING] stderr:     self._mainloop()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 460, in _mainloop
[WARNING] stderr:     EventLoop.idle()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/kivy/base.py", line 340, in idle
[WARNING] stderr:     self.dispatch_input()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/kivy/base.py", line 325, in dispatch_input
[WARNING] stderr:     post_dispatch_input(*pop(0))
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/kivy/base.py", line 291, in post_dispatch_input
[WARNING] stderr:     wid.dispatch('on_touch_up', me)
[WARNING] stderr:   File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7797)
[WARNING] stderr:   File "/storage/emulated/0/fest_app_home/kivymd/ripplebehavior.py", line 68, in on_touch_up
[WARNING] stderr:     return super(CommonRipple, self).on_touch_up(touch)
[WARNING] stderr:   File "/storage/emulated/0/fest_app_home/kivymd/button.py", line 206, in on_touch_up
[WARNING] stderr:     return super(BaseButton, self).on_touch_up(touch)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.6/site-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up
[WARNING] stderr:     self.dispatch('on_release')
[WARNING] stderr:   File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7752)
[WARNING] stderr:   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch (kivy/_event.c:13511)
[WARNING] stderr:   File "kivy/_event.pyx", line 1138, in kivy._event.EventObservers._dispatch (kivy/_event.c:13040)
[WARNING] stderr:   File "<string>", line 68, in <lambda>
[WARNING] stderr:   File "/storage/emulated/0/fest_app_home/main.py", line 148, in back
[WARNING] stderr:     self.path_back.pop()
[WARNING] stderr: IndexError: pop from empty list
